#!/usr/bin/env python3
"""
AI Code Detector — Enhanced
Identifies AI-generated code using multiple heuristics and outputs
structured results for CI/CD integration.
"""

import os
import re
import math
import sys
import json
from pathlib import Path
from typing import List, Dict, Any, Optional, Tuple
from collections import Counter
import argparse
import subprocess


# ─────────────────────────────────────────────────────────────────────────────
# Constants
# ─────────────────────────────────────────────────────────────────────────────

VERSION = "1.2.0"

SCAN_EXTENSIONS = {
    ".py", ".js", ".ts", ".jsx", ".tsx", ".java", ".go", ".rb",
    ".php", ".c", ".cpp", ".h", ".cs", ".swift", ".rs", ".kt"
}

AI_COMMIT_PATTERNS = [
    r"generated by",
    r"created by (AI|GPT|LLM|Copilot|Claude|Gemini|assistant)",
    r"via (Copilot|ChatGPT|Claude|Gemini|Codeium|Tabnine)",
    r"using (ChatGPT|Claude|Gemini|Copilot)",
    r"with (Claude|ChatGPT|Copilot|AI assistance)",
    r"AI[-\s]?(assisted|generated|authored|written)",
    r"copilot[- ]generated",
    r"gemini[- ]generated",
    r"llm[- ]generated",
]

AI_CODE_PATTERNS = [
    # Explicit AI signatures
    (r"Generated by (Copilot|ChatGPT|Claude|Gemini|Codeium)", 0.5, "Explicit AI signature"),
    (r"Created with (assistance from|help from|Copilot|ChatGPT|Claude)", 0.5, "Explicit AI attribution"),
    (r"@generated\b", 0.4, "Generated annotation"),
    (r"This (code|file|module|class|function) was (generated|created|written) by", 0.4, "AI authorship comment"),

    # AI-style verbose explanatory comments
    (r"(//|#)\s+This (function|method|class|module) (does|will|is used to|handles|manages|provides)", 0.15, "Verbose function description"),
    (r"(//|#)\s+The purpose of this (function|method|class|module|code) is", 0.15, "Purpose comment"),
    (r"(//|#)\s+This (ensures|guarantees|handles|prevents|checks|validates) that", 0.1, "AI-style guard comment"),
    (r"(//|#)\s+Step \d+[\.:]\s+\w+", 0.1, "Numbered step comments"),
    (r"(//|#)\s+[A-Z][a-z]+ (the|a|an) \w+ (to|from|with|by|for|in|of)\b", 0.08, "Sentence-case inline comment"),

    # Unimplemented stubs
    (r"raise NotImplementedError", 0.1, "NotImplementedError stub"),
    (r"throw new NotImplementedException", 0.1, "NotImplementedException stub"),
    (r"(//|#)\s*TODO\s*[:–-]?\s*(implement|add|fix|write|complete)\b", 0.1, "TODO stub"),
    (r"return (null|None|undefined);\s*(//|#).*implement", 0.15, "Null return with implement comment"),

    # Placeholder names
    (r"\b(foo|bar|baz|qux)\s*[=:(]", 0.1, "Placeholder variable names"),
    (r"class\s+(Example|Sample|Demo|MyClass|TestClass|Placeholder)\b", 0.15, "Placeholder class name"),
    (r"def\s+(my_function|temp_func|helper_function|do_something)\b", 0.15, "Placeholder function name"),
    (r"function\s+(myFunction|tempFunc|helperFunction|doSomething)\b", 0.15, "Placeholder function name"),
]

HUMAN_SIGNALS = [
    (r"(wtf|hack|kludge|workaround|shim|band-?aid)", -0.1),
    (r"(git blame|bisect|revert|hotfix)", -0.05),
    (r"(legacy|deprecated|old|ancient|crusty)", -0.05),
    (r"(prof(ile|iling)|perf|benchmark|flamegraph)", -0.05),
]


# ─────────────────────────────────────────────────────────────────────────────
# Detector
# ─────────────────────────────────────────────────────────────────────────────

class AICodeDetector:
    """
    Detects AI-generated code committed to a git repository.

    Scoring bands:
        0.0 – 0.39  → clean (no action)
        0.40 – 0.69 → possible AI  (flag for review)
        0.70 – 1.0  → likely AI    (requires extra review / blocks merge)
    """

    def __init__(self, repo_path: str = ".", verbose: bool = False):
        self.repo_path = Path(repo_path).resolve()
        self.verbose = verbose
        self.findings: List[Dict[str, Any]] = []

    # ── public API ────────────────────────────────────────────────────────────

    def scan_commit(self, commit_hash: str = "HEAD") -> List[Dict[str, Any]]:
        self._log(f"AI Code Detector v{VERSION}")
        self._log(f"Repo  : {self.repo_path}")
        self._log(f"Commit: {commit_hash}\n")

        commit_info = self._get_commit_info(commit_hash)
        if not commit_info:
            self._log("[ERROR] Could not retrieve commit info.", force=True)
            return []

        # Analyse commit message
        msg_score, msg_reasons = self._analyze_commit_message(commit_info["message"])
        if msg_score > 0.3:
            self.findings.append({
                "type": "commit_message",
                "confidence": round(msg_score, 2),
                "details": msg_reasons,
                "value": commit_info["message"][:120],
                "requires_review": msg_score >= 0.7,
            })

        # Analyse changed files
        files = self._get_changed_files(commit_hash)
        self._log(f"Files changed: {len(files)}")

        for file_path in files:
            if not self._should_scan(file_path):
                self._log(f"  skip  {file_path}")
                continue

            full_path = self.repo_path / file_path
            if not full_path.exists():
                self._log(f"  gone  {file_path}")
                continue

            score, indicators = self._analyze_file(full_path)
            self._log(f"  {score:.2f}  {file_path}  [{', '.join(indicators[:3])}]")

            if score >= 0.4:
                self.findings.append({
                    "type": "file_content",
                    "file": file_path,
                    "confidence": round(score, 2),
                    "indicators": indicators,
                    "requires_review": score >= 0.7,
                })

        self._print_report()
        return self.findings

    def should_block(self) -> bool:
        return any(f.get("requires_review") for f in self.findings)

    def to_json(self) -> str:
        return json.dumps(
            {
                "version": VERSION,
                "blocked": self.should_block(),
                "findings": self.findings,
            },
            indent=2,
        )

    # ── git helpers ───────────────────────────────────────────────────────────

    def _git(self, *args: str) -> str:
        result = subprocess.run(
            ["git", *args],
            cwd=self.repo_path,
            capture_output=True,
            text=True,
            check=True,
        )
        return result.stdout.strip()

    def _get_commit_info(self, commit_hash: str) -> Optional[Dict]:
        try:
            message = self._git("show", "-s", "--format=%s%n%b", commit_hash)
            return {"message": message, "hash": commit_hash}
        except Exception as e:
            self._log(f"[git error] {e}", force=True)
            return None

    def _get_changed_files(self, commit_hash: str) -> List[str]:
        try:
            out = self._git(
                "diff-tree", "--no-commit-id", "--name-only", "-r", commit_hash
            )
            return [f for f in out.splitlines() if f]
        except Exception as e:
            self._log(f"[git error] {e}", force=True)
            return []

    # ── analysis ──────────────────────────────────────────────────────────────

    def _should_scan(self, file_path: str) -> bool:
        return Path(file_path).suffix.lower() in SCAN_EXTENSIONS

    def _analyze_commit_message(self, message: str) -> Tuple[float, List[str]]:
        score = 0.0
        reasons: List[str] = []
        lower = message.lower()

        for pattern in AI_COMMIT_PATTERNS:
            if re.search(pattern, lower):
                score += 0.5
                reasons.append("Explicit AI tool mention in commit message")
                break

        words = len(message.split())
        if words > 60:
            score += 0.2
            reasons.append(f"Unusually long commit message ({words} words)")
        elif words < 4:
            score -= 0.1

        if re.search(r"(\*\*|__).*(\*\*|__)", message):
            score += 0.1
            reasons.append("Markdown bold formatting in commit message")

        bullet_lines = sum(1 for l in message.splitlines() if re.match(r"^\s*[-*+]\s", l))
        if bullet_lines >= 3:
            score += 0.15
            reasons.append(f"Bullet-point structure ({bullet_lines} bullets)")

        if re.search(r"^#{1,3}\s", message, re.MULTILINE):
            score += 0.1
            reasons.append("Markdown headings in commit message")

        return min(score, 1.0), reasons

    def _analyze_file(self, file_path: Path) -> Tuple[float, List[str]]:
        score = 0.0
        indicators: List[str] = []

        try:
            content = file_path.read_text(encoding="utf-8", errors="ignore")
        except Exception as e:
            return 0.0, [f"Read error: {e}"]

        lines = content.splitlines()
        total_lines = max(len(lines), 1)

        for pattern, weight, label in AI_CODE_PATTERNS:
            matches = re.findall(pattern, content, re.IGNORECASE)
            if matches:
                score += weight * min(len(matches), 3)
                indicators.append(f"{label} (×{len(matches)})" if len(matches) > 1 else label)

        for pattern, weight in HUMAN_SIGNALS:
            if re.search(pattern, content, re.IGNORECASE):
                score += weight

        comment_lines = sum(
            1 for l in lines
            if re.match(r"^\s*(//|#|/\*|\*|\"\"\")", l)
        )
        comment_ratio = comment_lines / total_lines
        if comment_ratio > 0.45:
            score += 0.2
            indicators.append(f"Very high comment density ({comment_ratio:.0%})")
        elif comment_ratio > 0.30:
            score += 0.1
            indicators.append(f"High comment density ({comment_ratio:.0%})")
        elif comment_ratio < 0.04:
            score -= 0.05

        fn_count = len(re.findall(r"\b(def |function |func |sub )\s*\w+", content))
        cls_count = len(re.findall(r"\b(class |struct |interface )\s*\w+", content))
        total_units = fn_count + cls_count
        density = total_units / (total_lines / 10)
        if density > 1.5 and total_units > 8:
            score += 0.15
            indicators.append(f"High function/class density ({total_units} in {total_lines} lines)")

        non_blank = [l.strip() for l in lines if l.strip()]
        if non_blank:
            top_count = Counter(non_blank).most_common(1)[0][1]
            if top_count > max(8, total_lines * 0.06):
                score += 0.15
                indicators.append(f"Repetitive line pattern (×{top_count})")

        entropy = self._entropy(content)
        if entropy > 4.8:
            score += 0.1
            indicators.append(f"High character entropy ({entropy:.2f})")
        elif entropy < 3.2 and total_lines > 20:
            score -= 0.05

        docstring_blocks = len(re.findall(r'("""|\'\'\')', content))
        if docstring_blocks > 6:
            score += 0.1
            indicators.append(f"Many docstring blocks ({docstring_blocks // 2})")

        return round(min(max(score, 0.0), 1.0), 3), indicators

    @staticmethod
    def _entropy(text: str) -> float:
        if not text:
            return 0.0
        freq = Counter(text)
        n = len(text)
        return -sum((c / n) * math.log2(c / n) for c in freq.values())

    # ── reporting ─────────────────────────────────────────────────────────────

    def _log(self, msg: str, force: bool = False):
        if self.verbose or force:
            print(msg)

    def _print_report(self):
        if not self.findings:
            print("\n✅  No AI-generated code detected.")
            return

        high = [f for f in self.findings if f.get("requires_review")]
        low  = [f for f in self.findings if not f.get("requires_review")]

        print("\n" + "═" * 62)
        print("  AI CODE DETECTION REPORT")
        print("═" * 62)

        if high:
            print(f"\n🔴  REQUIRES EXTRA REVIEW  ({len(high)} finding{'s' if len(high) > 1 else ''})")
            for f in high:
                self._print_finding(f)

        if low:
            print(f"\n🟡  POSSIBLE AI  ({len(low)} finding{'s' if len(low) > 1 else ''})")
            for f in low:
                self._print_finding(f)

        status = "BLOCKED" if self.should_block() else "FLAGGED FOR REVIEW"
        print(f"\n{'─' * 62}")
        print(f"  Result: {status}")
        print("═" * 62 + "\n")

    @staticmethod
    def _print_finding(f: Dict):
        if f["type"] == "commit_message":
            print(f"\n  • Commit message  (confidence: {f['confidence']:.0%})")
            for d in f.get("details", []):
                print(f"      – {d}")
        else:
            print(f"\n  • {f['file']}  (confidence: {f['confidence']:.0%})")
            for ind in f.get("indicators", [])[:4]:
                print(f"      – {ind}")


# ─────────────────────────────────────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Detect AI-generated code in git commits",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Exit codes:
  0  clean / flagged but not blocking
  1  AI code detected and --block flag set
""",
    )
    parser.add_argument("--repo-path", default=".", help="Path to git repository")
    parser.add_argument("--commit", default="HEAD", help="Commit hash to scan (default: HEAD)")
    parser.add_argument("--block", action="store_true", help="Exit 1 if high-confidence AI code found")
    parser.add_argument(
        "--json-output",
        default="",
        metavar="FILE",
        help="Write JSON results to FILE (keeps stdout clean for human-readable report)",
    )
    parser.add_argument("--verbose", action="store_true", help="Print debug info")
    parser.add_argument("--version", action="version", version=f"%(prog)s {VERSION}")
    args = parser.parse_args()

    detector = AICodeDetector(repo_path=args.repo_path, verbose=args.verbose)
    detector.scan_commit(args.commit)

    # Write JSON to a dedicated file so it never mixes with stdout
    if args.json_output:
        output_path = Path(args.json_output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(detector.to_json(), encoding="utf-8")
        print(f"\nJSON results written to: {args.json_output}")

    if args.block and detector.should_block():
        print("\n🚫 AI-generated code detected — blocking merge until review is complete.")
        sys.exit(1)

    sys.exit(0)


if __name__ == "__main__":
    main()