name: Security

on:
  pull_request:
  push:
    branches: [main]

jobs:
  security:
    uses: org/security-guardrails/ci/github/security-orchestrator.yml@v1
    secrets:
      FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
